# -*- coding: utf-8 -*-
"""handwritten_text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1leVBShfdw3SrrbqQe0su84sbSUEAMlWq
"""

!sudo apt update
!sudo apt install tesseract-ocr -y
!pip install pytesseract opencv-python-headless pillow

import cv2
import pytesseract
from PIL import Image
!tesseract --version

def recognize_handwriting(image_path):
    image = cv2.imread(image_path)
    if image is None:
        print("Error: Could not open or find the image.")
        return ""
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    _, thresh = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (2, 2))
    processed_img = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, kernel)
    extracted_text = pytesseract.image_to_string(processed_img, lang='eng')
    return extracted_text

from google.colab import files
uploaded = files.upload()

image_path = list(uploaded.keys())[0]
text = recognize_handwriting(image_path)
print("Extracted Text:\n", text)